<?php    
    define('DBhost','localhost');
    define('DBuser','aze624');
    define('DBpass','ay2111!!');
    define('DBname','aze624');
    //define('DBhost','ashram777.cafe24.com');
    //define('DBuser','ashram777');
    //define('DBpass','dhanstjd77!');
    //define('DBname','ashram777');
?>